version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name:postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      -"5432:5432"
    values:
      -postgres_data:/var/lib/postgressql/data

  volumes:
    postgres_data:
